version: "3"

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 8088:8088
    volumes:
      - 'C:\DevOps\Exercises\Workshop 5\nginx.conf:/etc/nginx/nginx.conf'   

  redis: 
    image: 'docker.io/library/redis:latest'
    ports: 
     - "6379:6379"
  cliapp:
    build:
        context: 'C:\DevOps\Exercises\Workshop 5\dockerfiles'
        dockerfile: Dockerfile.cliapp
    environment:
     - REDIS_PORT=6379
     - REDIS_HOST=redis
  webapp:
    build:
        context: 'C:\DevOps\Exercises\Workshop 5\dockerfiles'
        dockerfile: Dockerfile.webapp
    ports: 
     - "8080:80"
    environment:
     - REDIS_PORT=6379
     - REDIS_HOST=redis
    